//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class AKO_AL_ADF {
        displayName = "Ako's Altis (ADF)";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        priority = 0;
    };
    class AKO_TA_TLA {
        displayName = "Ako's Tanoa (TLA)";
        side = 2;
        flag = "\A3\Ui_f\data\Map\Markers\Flags\tanoa_ca.paa";
        icon = "\A3\Ui_f\data\Map\Markers\Flags\tanoa_ca.paa";
        priority = 0;
    };
    class AKO_RU_MSV {
        displayName = "Ako's Russia (MSV)";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        priority = 0;
    };
    class AKO_RU_VDV {
        displayName = "Ako's Russia (VDV)";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        priority = 0;
    };
    class AKO_RU_VMF {
        displayName = "Ako's Russia (VMF)";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vmf_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vmf_CO.paa";
        priority = 0;
    };
    class AKO_US_USMC {
        displayName = "Ako's USA (USMC)";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
        class AKO_US_RG {
        displayName = "Ako's USA (RANGERS)";
        side = 1;
        flag = "\rhsusf\addons\rhsusf_main\data\flag_map\flag_us_co.paa";
        icon = "\rhsusf\addons\rhsusf_main\data\flag_map\flag_us_co.paa";
        priority = 0;
    };
};
