//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////



    class rhs_vdv_rifleman;
    class rhs_vdv_rifleman_OCimport_01 : rhs_vdv_rifleman { scope = 0; class EventHandlers; };
    class rhs_vdv_rifleman_OCimport_02 : rhs_vdv_rifleman_OCimport_01 { class EventHandlers; };

    class rhs_bmd1;
    class rhs_bmd1_OCimport_01 : rhs_bmd1 { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd1_OCimport_02 : rhs_bmd1_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics1;
            class GPMGTurretBMD1;
            class LeftBack1;
            class RightBack1;
            class MainBack1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class rhs_bmd2;
    class rhs_bmd2_OCimport_01 : rhs_bmd2 { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd2_OCimport_02 : rhs_bmd2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics1;
            class GPMGTurretBMD1;
            class LeftBack1;
            class RightBack1;
            class MainBack1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class rhs_bmd4_vdv;
    class rhs_bmd4_vdv_OCimport_01 : rhs_bmd4_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd4_vdv_OCimport_02 : rhs_bmd4_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class LeftBack;
            class RightBack;
            class MainFront;
        };
    };

    class rhs_bmd4ma_vdv;
    class rhs_bmd4ma_vdv_OCimport_01 : rhs_bmd4ma_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd4ma_vdv_OCimport_02 : rhs_bmd4ma_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class GPMGTurret2;
            class RightBack;
            class LeftBack;
            class MiddleBack;
        };
    };

    class rhs_ka60_c;
    class rhs_ka60_c_OCimport_01 : rhs_ka60_c { scope = 0; class EventHandlers; class Turrets; };
    class rhs_ka60_c_OCimport_02 : rhs_ka60_c_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class RHS_Ka52_vvsc;
    class RHS_Ka52_vvsc_OCimport_01 : RHS_Ka52_vvsc { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Ka52_vvsc_OCimport_02 : RHS_Ka52_vvsc_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class RHS_Mi8T_vdv;
    class RHS_Mi8T_vdv_OCimport_01 : RHS_Mi8T_vdv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8T_vdv_OCimport_02 : RHS_Mi8T_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class RHS_Mi8mt_vdv;
    class RHS_Mi8mt_vdv_OCimport_01 : RHS_Mi8mt_vdv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8mt_vdv_OCimport_02 : RHS_Mi8mt_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class BackTurret;
        };
    };

    class RHS_Mi8MTV3_heavy_vdv;
    class RHS_Mi8MTV3_heavy_vdv_OCimport_01 : RHS_Mi8MTV3_heavy_vdv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8MTV3_heavy_vdv_OCimport_02 : RHS_Mi8MTV3_heavy_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class SideTurret;
            class BackTurret;
            class FrontTurret;
        };
    };

    class rhs_mig29sm_vvsc;
    class rhs_mig29sm_vvsc_OCimport_01 : rhs_mig29sm_vvsc { scope = 0; class EventHandlers; };
    class rhs_mig29sm_vvsc_OCimport_02 : rhs_mig29sm_vvsc_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_Su25SM_vvsc;
    class RHS_Su25SM_vvsc_OCimport_01 : RHS_Su25SM_vvsc { scope = 0; class EventHandlers; };
    class RHS_Su25SM_vvsc_OCimport_02 : RHS_Su25SM_vvsc_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_T50_vvs_blueonblue;
    class RHS_T50_vvs_blueonblue_OCimport_01 : RHS_T50_vvs_blueonblue { scope = 0; class EventHandlers; };
    class RHS_T50_vvs_blueonblue_OCimport_02 : RHS_T50_vvs_blueonblue_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_TU95MS_vvs_old;
    class RHS_TU95MS_vvs_old_OCimport_01 : RHS_TU95MS_vvs_old { scope = 0; class EventHandlers; class Turrets; };
    class RHS_TU95MS_vvs_old_OCimport_02 : RHS_TU95MS_vvs_old_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class MainTurret2;
            class MainTurret3;
            class MainTurret4;
            class MainTurret5;
            class RearTurret;
            class MainTurret6;
        };
    };

    class rhsgref_mi24g_CAS;
    class rhsgref_mi24g_CAS_OCimport_01 : rhsgref_mi24g_CAS { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_mi24g_CAS_OCimport_02 : rhsgref_mi24g_CAS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class rhs_mi28n_vvsc;
    class rhs_mi28n_vvsc_OCimport_01 : rhs_mi28n_vvsc { scope = 0; class EventHandlers; class Turrets; };
    class rhs_mi28n_vvsc_OCimport_02 : rhs_mi28n_vvsc_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_kamaz5350_vdv;
    class rhs_kamaz5350_vdv_OCimport_01 : rhs_kamaz5350_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_kamaz5350_vdv_OCimport_02 : rhs_kamaz5350_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class rhs_kamaz5350_ammo_vdv;
    class rhs_kamaz5350_ammo_vdv_OCimport_01 : rhs_kamaz5350_ammo_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_kamaz5350_ammo_vdv_OCimport_02 : rhs_kamaz5350_ammo_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_03;
        };
    };

    class rhs_kamaz5350_open_vdv;
    class rhs_kamaz5350_open_vdv_OCimport_01 : rhs_kamaz5350_open_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_kamaz5350_open_vdv_OCimport_02 : rhs_kamaz5350_open_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class O_UAV_02_dynamicLoadout_F;
    class O_UAV_02_dynamicLoadout_F_OCimport_01 : O_UAV_02_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class O_UAV_02_dynamicLoadout_F_OCimport_02 : O_UAV_02_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class HE_Ababil3_Opfor;
    class HE_Ababil3_Opfor_OCimport_01 : HE_Ababil3_Opfor { scope = 0; class EventHandlers; class Turrets; };
    class HE_Ababil3_Opfor_OCimport_02 : HE_Ababil3_Opfor_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class JS_JC_SU35;
    class JS_JC_SU35_OCimport_01 : JS_JC_SU35 { scope = 0; class EventHandlers; };
    class JS_JC_SU35_OCimport_02 : JS_JC_SU35_OCimport_01 { scope = 0; class EventHandlers; };


    class ru_vdv_sergeant : rhs_vdv_rifleman_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Sergeant";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_grn","rhs_6b47_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_grn","rhs_6b47_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK12_GP34_black","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AK12_GP34_black","Binocular"};

        magazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_1Rnd_HE_GP25_M","CUP_30Rnd_545x39_AK12_M","CUP_1Rnd_HE_GP25_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_1Rnd_HE_GP25_M","CUP_30Rnd_545x39_AK12_M","CUP_1Rnd_HE_GP25_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK12_GP34_black","","rhs_acc_perst1ik_ris","rhs_acc_rakursPM",{"CUP_30Rnd_545x39_AK12_M",30},{"CUP_1Rnd_HE_GP25_M",1},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_grn",{{"rhs_mag_rgo",5,1},{"CUP_1Rnd_HE_GP25_M",10,1},{"CUP_30Rnd_545x39_AK12_M",9,30}}},{},"rhs_6b47_ess","rhs_facewear_6m2_1",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_efreitor : ru_vdv_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Efreitor";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_6m2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_6m2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK12_AFG_black","rhs_weap_rpg26"};
        respawnWeapons[] = {"CUP_arifle_AK12_AFG_black","rhs_weap_rpg26"};

        magazines[] = {"CUP_30Rnd_545x39_AK12_M","rhs_rpg26_mag","CUP_30Rnd_545x39_AK12_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK12_M","rhs_rpg26_mag","CUP_30Rnd_545x39_AK12_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK12_AFG_black","","rhs_acc_perst1ik_ris","rhs_acc_1p87",{"CUP_30Rnd_545x39_AK12_M",30},{},""},{"rhs_weap_rpg26","","","",{"rhs_rpg26_mag",1},{},""},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",5,1},{"CUP_30Rnd_545x39_AK12_M",9,30}}},{},"rhs_6b47_6m2","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_rifleman_ak12 : ru_vdv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Rifleman (AK-12)";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b47","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b47","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK12_black"};
        respawnWeapons[] = {"CUP_arifle_AK12_black"};

        magazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK12_black","","rhs_acc_perst1ik_ris","rhs_acc_1p87",{"CUP_30Rnd_545x39_AK12_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",2},{"rhs_mag_rgo",5,1},{"CUP_30Rnd_545x39_AK12_M",8,30}}},{},"rhs_6b47","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_rifleman_ak74m : ru_vdv_rifleman_ak12 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Rifleman (AK-74M)";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_railed_afg"};
        respawnWeapons[] = {"CUP_arifle_AK74M_railed_afg"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_railed_afg","","rhs_acc_perst1ik_ris","rhs_acc_1p87",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",2},{"rhs_mag_rgo",5,1},{"CUP_30Rnd_545x39_AK74_plum_M",8,30}}},{},"rhs_6b47_bala","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_rifleman_asval : ru_vdv_rifleman_ak74m {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Rifleman (AS Val)";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_ess_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b47_ess_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AS_VAL"};
        respawnWeapons[] = {"CUP_arifle_AS_VAL"};

        magazines[] = {"CUP_20Rnd_9x39_SP5_VSS_M","CUP_20Rnd_9x39_SP5_VSS_M"};
        respawnMagazines[] = {"CUP_20Rnd_9x39_SP5_VSS_M","CUP_20Rnd_9x39_SP5_VSS_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AS_VAL","","rhs_acc_perst1ik_ris","rhs_acc_pkas",{"CUP_20Rnd_9x39_SP5_VSS_M",20},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",2},{"rhs_mag_rgo",2,1},{"CUP_20Rnd_9x39_SP5_VSS_M",9,20}}},{},"rhs_6b47_ess_bala","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_medic : ru_vdv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Medic";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b47","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b47","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK12_black"};
        respawnWeapons[] = {"CUP_arifle_AK12_black"};

        magazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};

        backpack = "B_Kitbag_sgg";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK12_black","","rhs_acc_perst1ik_ris","rhs_acc_1p87",{"CUP_30Rnd_545x39_AK12_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",2},{"rhs_mag_rgo",5,1},{"CUP_30Rnd_545x39_AK12_M",8,30}}},{"B_Kitbag_sgg",{{"Medikit",2},{"FirstAidKit",5}}},"rhs_6b47","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_autorifleman : ru_vdv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Auto Rifleman";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_mg","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_mg","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_RPK74M"};
        respawnWeapons[] = {"CUP_arifle_RPK74M"};

        magazines[] = {"CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M","CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M","CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M"};

        backpack = "rhs_rd54_emr1";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_RPK74M","","rhs_acc_perst1ik_ris","CUP_optic_PSO_1_1_open",{"CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_mg",{{"FirstAidKit",3},{"rhs_mag_rgo",5,1},{"CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M",8,30}}},{"rhs_rd54_emr1",{{"CUP_30Rnd_TE1_Red_Tracer_545x39_AK74M_M",10,30}}},"rhs_6b47_bala","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_machinegunner : ru_vdv_autorifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Machine Gunner";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_mg","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_mg","rhs_6b47_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_Pecheneg_B50_vfg"};
        respawnWeapons[] = {"CUP_lmg_Pecheneg_B50_vfg"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M"};

        backpack = "rhs_rk_sht_30_emr";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_Pecheneg_B50_vfg","","","rhs_acc_pkas",{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",100},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_mg",{{"FirstAidKit",4},{"rhs_mag_rgo",2,1},{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",2,100}}},{"rhs_rk_sht_30_emr",{{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",5,100}}},"rhs_6b47_bala","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_heli_pilot : ru_vdv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Helicopter Pilot";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_light","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U"};
        respawnWeapons[] = {"CUP_arifle_AKS74U"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"FirstAidKit",3},{"CUP_30Rnd_545x39_AK74M_M",4,30}}},{},"rhs_zsh7a_mike_green_alt","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_heli_crewman : ru_vdv_heli_pilot {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Helicopter Crew";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_light","rhs_zsh7a_mike_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_zsh7a_mike_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U"};
        respawnWeapons[] = {"CUP_arifle_AKS74U"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"FirstAidKit",3},{"CUP_30Rnd_545x39_AK74M_M",4,30}}},{},"rhs_zsh7a_mike_green","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_jet_pilot : ru_vdv_heli_pilot {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Jet Pilot";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_df15_tan";

        linkedItems[] = {"CMU33PTan","rhs_zsh7a_alt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CMU33PTan","rhs_zsh7a_alt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AKS74U","Binocular"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "B_Parachute";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_df15_tan",{{"FirstAidKit",5}}},{"CMU33PTan",{{"FirstAidKit",4},{"CUP_30Rnd_545x39_AK74M_M",5,30},{"rhs_mag_rgo",2,1}}},{"B_Parachute",{}},"rhs_zsh7a_alt","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


    class ru_vdv_crewman : ru_vdv_heli_pilot {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Crewman";
        side = 0;
        faction = "ako_ru_vdv";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_vkpo_gloves";

        linkedItems[] = {"rhs_6b45_light","rhs_6b48","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_6b48","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U"};
        respawnWeapons[] = {"CUP_arifle_AKS74U"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_vkpo_gloves",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"FirstAidKit",3},{"CUP_30Rnd_545x39_AK74M_M",4,30}}},{},"rhs_6b48","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_bmd1 : rhs_bmd1_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV BMD-1";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_crewman"; };
            class CommanderOptics1 : CommanderOptics1 { gunnerType = "ru_vdv_crewman"; };
            class GPMGTurretBMD1 : GPMGTurretBMD1 { gunnerType = ""; };
            class LeftBack1 : LeftBack1 { gunnerType = ""; };
            class RightBack1 : RightBack1 { gunnerType = ""; };
            class MainBack1 : MainBack1 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmd\data\sa_bmd2_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmd\data\sa_bmd1_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmd\data\sa_bmd2_03_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_vdv_bmd2 : rhs_bmd2_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV BMD-2";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_crewman"; };
            class CommanderOptics1 : CommanderOptics1 { gunnerType = "ru_vdv_crewman"; };
            class GPMGTurretBMD1 : GPMGTurretBMD1 { gunnerType = ""; };
            class LeftBack1 : LeftBack1 { gunnerType = ""; };
            class RightBack1 : RightBack1 { gunnerType = ""; };
            class MainBack1 : MainBack1 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmd\data\sa_bmd2_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmd\data\sa_bmd2_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmd\data\sa_bmd2_03_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_vdv_bmd4 : rhs_bmd4_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV BMD-4";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_crewman"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = ""; };
            class LeftBack : LeftBack { gunnerType = ""; };
            class RightBack : RightBack { gunnerType = ""; };
            class MainFront : MainFront { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmd_34\data\rhs_bmd3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmd_34\data\rhs_bmd4_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmd_34\data\rhs_bmd4_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_sprut\data\bmd34roadwheel_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_vdv_bmd4m : rhs_bmd4ma_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV BMD-4M (A)";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_crewman"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = ""; };
            class GPMGTurret2 : GPMGTurret2 { gunnerType = ""; };
            class RightBack : RightBack { gunnerType = ""; };
            class LeftBack : LeftBack { gunnerType = ""; };
            class MiddleBack : MiddleBack { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_ka60 : rhs_ka60_c_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Ka-60";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "ru_vdv_heli_pilot"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_a3retex\Data\heli_light_02_ext_c_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "vvs_camo";

    };

    class ru_vdv_ka52 : RHS_Ka52_vvsc_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Ka-52";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_heli_pilot"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_mi8t : RHS_Mi8T_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Mi-8T";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "ru_vdv_heli_pilot"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo1_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_a2port_air\mi17\data\mi8t\camo\mi8t_tv2_g_camo1_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo2";

    };

    class ru_vdv_mi8mt : RHS_Mi8mt_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Mi-8MT";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "ru_vdv_heli_pilot"; };
            class MainTurret : MainTurret { gunnerType = "ru_vdv_heli_crewman"; };
            class BackTurret : BackTurret { gunnerType = "ru_vdv_heli_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo1_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo2";

    };

    class ru_vdv_mi8mtv3 : RHS_Mi8MTV3_heavy_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Mi-8MTV-3";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "ru_vdv_heli_pilot"; };
            class SideTurret : SideTurret { gunnerType = "ru_vdv_heli_crewman"; };
            class BackTurret : BackTurret { gunnerType = "ru_vdv_heli_crewman"; };
            class FrontTurret : FrontTurret { gunnerType = "ru_vdv_heli_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo1_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo2";

    };

    class ru_vdv_mig29sm : rhs_mig29sm_vvsc_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV MiG-29SM";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_jet_pilot";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_su25 : RHS_Su25SM_vvsc_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Su-25";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_jet_pilot";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_a2port_air\su25\data\su25_body1_rus_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_a2port_air\su25\data\su25_body2_rus_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class ru_vdv_t50_2013 : RHS_T50_vvs_blueonblue_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV T-50 (2013)";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_jet_pilot";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_tu95ms6 : RHS_TU95MS_vvs_old_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Tu-95MS6 Bear";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_jet_pilot";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_jet_pilot"; };
            class MainTurret2 : MainTurret2 { gunnerType = "ru_vdv_jet_pilot"; };
            class MainTurret3 : MainTurret3 { gunnerType = "ru_vdv_jet_pilot"; };
            class MainTurret4 : MainTurret4 { gunnerType = "ru_vdv_jet_pilot"; };
            class MainTurret5 : MainTurret5 { gunnerType = "ru_vdv_jet_pilot"; };
            class RearTurret : RearTurret { gunnerType = "ru_vdv_jet_pilot"; };
            class MainTurret6 : MainTurret6 { gunnerType = "ru_vdv_jet_pilot"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,''];_unit setObjectTextureGlobal [1,''];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\rhs_decals\Data\Labels\Aviation\star_old_ca.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\rhs_decals\Data\Numbers\AviaRed4\2_ca.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\rhs_decals\Data\Numbers\AviaRed4\3_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Old";

    };

    class ru_vdv_mi24g : rhsgref_mi24g_CAS_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Mi-24G";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_heli_pilot"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_mi28n : rhs_mi28n_vvsc_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Mi-28N";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_heli_pilot";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "ru_vdv_heli_pilot"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_kamaz : rhs_kamaz5350_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV KamAZ-5350";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_rifleman_ak74m";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_kamaz_ammo : rhs_kamaz5350_ammo_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV KamAZ-5350 (Ammo)";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_rifleman_ak74m";

        class Turrets : Turrets {
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_kamaz_open : rhs_kamaz5350_open_vdv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV KamAZ-5350 (Open)";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_rifleman_ak74m";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_k40a : O_UAV_02_dynamicLoadout_F_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV K-40A Ababil";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "O_UAV_AI";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_k40b : HE_Ababil3_Opfor_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV K-40B Kamikaze";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "O_UAV_AI";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_vdv_su35 : JS_JC_SU35_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "VDV Su-35 Flanker";
        side = 0;
        faction = "ako_ru_vdv";
        crew = "ru_vdv_jet_pilot";

        class Components {
            class TransportPylonsComponent {

                class Pylons {
					class pylon1
					{
						hardpoints[] = {"FIR_MISC"};
						attachment = "FIR_KAB500L_P_1rnd_M";
						priority = 1;
						maxweight = 500;
                        turret[] = {}; 		
						UIposition[] = {0.25,0.10};
					};		
                    class pylon2: pylon1
					{
						UIposition[] = {0.25,0.5};
						mirroredMissilePos = 1;
					};	
                    class pylon3: pylon1
					{
						UIposition[] = {0.25,0.0};
						mirroredMissilePos = 1;
					};
                    class pylon4: pylon1
					{
						UIposition[] = {0.15,0.10};
						mirroredMissilePos = 1;
					};
                    class pylon5: pylon1
					{
						UIposition[] = {0.15,0.5};
						mirroredMissilePos = 1;
					};
                    class pylon6: pylon1
					{
						UIposition[] = {0.15,0.0};
						mirroredMissilePos = 1;
					};
                    class pylon7: pylon1
					{
						UIposition[] = {0.5,0.5};
						mirroredMissilePos = 1;
					};
                    class pylon8: pylon1
					{
						UIposition[] = {0.5,0.0};
						mirroredMissilePos = 1;
					};
                    class pylon9
					{
						hardpoints[] = {"FIR_MISC"};
						attachment = "PylonMissile_1Rnd_BombCluster_02_cap_F";
						priority = 2;
						maxweight = 1000;
                        turret[] = {}; 		
						UIposition[] = {0.35,0.0.5};
					};	
                    class pylon10: pylon9
					{
						UIposition[] = {0.35,0.0};
						mirroredMissilePos = 1;
					};
                    
				};					
                
            };
        };

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\js_jc_su35\data\Su35_hull_co.paa'];_unit setObjectTextureGlobal [1,'\js_jc_su35\data\Su35_misc_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "RussianAFGreyDigital";

    };
