class CfgPatches {
    class AKO_AL_ADF {
        units[] = {
            "al_adf_sergeant",
            "al_adf_rifleman_g36",
            "al_adf_rifleman_g3a3",
            "al_adf_officer",
            "al_adf_aa_specialist",
            "al_adf_at_specialist",
            "al_adf_corporal",
            "al_adf_autorifleman",
            "al_adf_crewman",
            "al_adf_elite_rifleman",
            "al_adf_engineer",
            "al_adf_medic",
            "al_adf_machinegunner",
            "al_adf_marksman",
            "al_adf_t72b",
            "al_adf_t80u",
            "al_adf_gaz66_aa",
            "al_adf_uaz_dshkm",
            "al_adf_uaz_ags30",
            "al_adf_uaz_spg9",
            "al_adf_btr70",
            "al_adf_bmp2",
            "al_adf_bmp1"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsgref_c_troops",
            "A3_Characters_F",
            "rhs_c_troops",
            "rhs_cti_insurgents",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhsgref_c_vehicles_ret",
            "rhs_c_t72",
            "rhs_c_vehiclesounds",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "rhssaf_c_vehicles",
            "A3_Data_F_ParticleEffects",
            "rhs_c_trucks",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Soft_F_Offroad_01",
            "rhs_c_btr",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhsgref_c_a2port_armor"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_TA_TLA {
        units[] = {
            "ta_tla_sergeant",
            "ta_tla_rifleman_aks",
            "ta_tla_rifleman_fal",
            "ta_tla_medic",
            "ta_tla_marksman",
            "ta_tla_machinegunner",
            "ta_tla_crewman",
            "ta_tla_autorifleman",
            "ta_tla_driver",
            "ta_tla_engineer",
            "ta_tla_grenadier_rpg",
            "ta_tla_aa_specialist",
            "ta_tla_elite_rifleman",
            "ta_tla_uaz_dshkm",
            "ta_tla_uaz_spg9",
            "ta_tla_uaz_ags30",
            "ta_tla_btr70",
            "ta_tla_bmd1",
            "ta_tla_bmd2",
            "ta_tla_t72b_1985",
            "ta_tla_ural_aa",
            "ta_tla_ural_normal"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsgref_c_troops",
            "A3_Characters_F",
            "rhs_c_troops",
            "rhs_cti_insurgents",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhsgref_c_vehicles_ret",
            "rhs_c_a2port_car",
            "rhs_c_vehiclesounds",
            "rhssaf_c_vehicles",
            "A3_Soft_F_Offroad_01",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "rhs_c_btr",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_a2port_armor",
            "rhsgref_c_a2port_armor",
            "rhs_c_bmd",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_TK_ISIS {
        units[] = {
            "tk_isis_squad_leader",
            "tk_isis_rifleman_akm",
            "tk_isis_rifleman_m16",
            "tk_isis_crewman",
            "tk_isis_aa_specialist",
            "tk_isis_grenadier_m16a4",
            "tk_isis_grenadier_rpg",
            "tk_isis_elite_rifleman_m4a1",
            "tk_isis_elite_rifleman_mk17",
            "tk_isis_elite_autorifleman",
            "tk_isis_marksman",
            "tk_isis_machinegunner",
            "tk_isis_missileman",
            "tk_isis_medic",
            "tk_isis_engineer",
            "tk_isis_t72m",
            "tk_isis_t72b_1989",
            "tk_isis_bmp1",
            "tk_isis_bmp2",
            "tk_isis_btr80a",
            "tk_isis_zsu23",
            "tk_isis_m1025_m2",
            "tk_isis_m1025_mk19",
            "tk_isis_m1025_tow"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsgref_c_troops",
            "A3_Characters_F",
            "rhs_c_troops",
            "rhs_cti_insurgents",
            "rhssaf_c_troops",
            "MoeAnimations",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhsgref_c_vehicles_ret",
            "rhs_c_t72",
            "rhs_c_vehiclesounds",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "QAV_AbramsX",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "rhssaf_c_vehicles",
            "A3_Data_F_ParticleEffects",
            "rhs_c_btr",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhsgref_c_a2port_armor",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "rhsusf_vehicles",
            "A3_Soft_F_MRAP_01",
            "A3_Soft_F_Exp_MRAP_01"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_RU_MSV {
        units[] = {
            "ru_msv_ural_repair",
            "ru_msv_rifleman_ak12",
            "ru_msv_rifleman_ak74m",
            "ru_msv_rifleman_akm",
            "ru_msv_sergeant",
            "ru_msv_crewman",
            "ru_msv_tank_crewman",
            "ru_msv_efreitor",
            "ru_msv_machinegunner",
            "ru_msv_marksman",
            "ru_msv_engineer",
            "ru_msv_medic",
            "ru_msv_grenadier_rpg",
            "ru_msv_aa_specialist",
            "ru_msv_at_specialist",
            "ru_msv_officer",
            "ru_msv_worker",
            "ru_msv_btr80a",
            "ru_msv_btr70",
            "ru_msv_t72b_1989",
            "ru_msv_t72b3_2012",
            "ru_msv_t80u",
            "ru_msv_t80um",
            "ru_msv_t90_1992",
            "ru_msv_t90a_2006",
            "ru_msv_t90sm",
            "ru_msv_bmp1",
            "ru_msv_bmp2",
            "ru_msv_bmp3",
            "ru_msv_bmp3_vesna",
            "ru_msv_uaz",
            "ru_msv_uaz_open",
            "ru_msv_gaz_normal",
            "ru_msv_gaz_armed",
            "ru_msv_gaz_unarmed",
            "ru_msv_ural_normal",
            "ru_msv_ural_flatbed",
            "ru_msv_ural_open",
            "ru_msv_ural_open_flatbed",
            "ru_msv_ural_fuel",
            "ru_msv_ural_ammo",
            "ru_msv_ural_aa",
            "ru_msv_bm21",
            "ru_msv_grenadier_gp25",
            "ru_msv_grenadier_gp34",
            "ru_msv_driver",
            "ru_msv_brdm",
            "ru_msv_brdm_at",
            "ru_msv_salvager",
            "ru_msv_mortarman_gun",
            "ru_msv_mortarman_bipod",
            "ru_msv_uav_operator"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_a2port_car",
            "rhs_c_vehiclesounds",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "rhssaf_c_vehicles",
            "rhsgref_c_vehicles_ret",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "A3_Data_F_Curator",
            "cba_xeh",
            "rhs_c_troops",
            "A3_Characters_F",
            "rhs_cti_insurgents",
            "rhsgref_c_troops",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Air_F_Heli",
            "rhs_c_btr",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_a2port_armor",
            "rhsgref_c_a2port_armor",
            "rhs_c_t72",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "A3_Soft_F_Offroad_01",
            "rhs_c_cars",
            "A3_Soft_F_MRAP_02"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_RU_VDV {
        units[] = {
            "ru_vdv_sergeant",
            "ru_vdv_efreitor",
            "ru_vdv_rifleman_ak12",
            "ru_vdv_rifleman_ak74m",
            "ru_vdv_rifleman_asval",
            "ru_vdv_medic",
            "ru_vdv_autorifleman",
            "ru_vdv_machinegunner",
            "ru_vdv_heli_pilot",
            "ru_vdv_heli_crewman",
            "ru_vdv_jet_pilot",
            "ru_vdv_crewman",
            "ru_vdv_at_specialist",
            "ru_vdv_uav_operator",
            "ru_vdv_bmd1",
            "ru_vdv_bmd2",
            "ru_vdv_bmd4",
            "ru_vdv_bmd4m",
            "ru_vdv_ka60",
            "ru_vdv_ka52",
            "ru_vdv_mi8t",
            "ru_vdv_mi8mt",
            "ru_vdv_mi8mtv3",
            "ru_vdv_mig29sm",
            "ru_vdv_su25",
            "ru_vdv_t50_2013",
            "ru_vdv_tu95ms6",
            "ru_vdv_mi24g",
            "ru_vdv_mi28n",
            "ru_vdv_kamaz",
            "ru_vdv_kamaz_ammo",
            "ru_vdv_kamaz_open",
            "ru_vdv_k40a",
            "ru_vdv_k40b",
            "ru_vdv_su35",
            "ru_vdv_des_sergeant",
            "ru_vdv_des_efreitor_ak12",
            "ru_vdv_des_efreitor_ak74m",
            "ru_vdv_des_rifleman_ak74m",
            "ru_vdv_des_rifleman_ak103",
            "ru_vdv_des_rifleman_ak12",
            "ru_vdv_des_medic",
            "ru_vdv_des_engineer",
            "ru_vdv_des_grenadier_gp34",
            "ru_vdv_des_grenadier_rpg",
            "ru_vdv_des_machinegunner",
            "ru_vdv_des_autorifleman",
            "ru_vdv_des_aa_specialist",
            "ru_vdv_des_at_specialist",
            "ru_vdv_des_officer",
            "ru_vdv_des_marksman",
            "ru_vdv_des_driver",
            "ru_vdv_des_worker",
            "ru_vdv_des_uav_operator",
            "ru_vdv_des_crewman",
            "ru_vdv_des_tank_crewman",
            "ru_vdv_des_heli_pilot",
            "ru_vdv_des_heli_crew",
            "ru_vdv_des_jet_pilot",
            "ru_vdv_des_mortarman_gun",
            "ru_vdv_des_mortarman_bipod",
            "ru_vdv_spetsnaz_ak12",
            "ru_vdv_spetsnaz_ak104",
            "ru_vdv_spetsnaz_ak74m",
            "ru_vdv_spetsnaz_ak15",
            "ru_vdv_spetsnaz_aks74u",
            "ru_vdv_spetsnaz_svd",
            "ru_vdv_spetsnaz_pilot"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops",
            "A3_Characters_F",
            "rhs_cti_insurgents",
            "rhsgref_c_troops",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhs_c_bmd",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "rhssaf_c_vehicles",
            "rhsgref_c_vehicles_ret",
            "A3_Data_F_ParticleEffects",
            "rhs_c_a3retex",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Beta_Heli_Transport_01",
            "rhsusf_c_melb",
            "rhsgref_c_air",
            "rhs_c_a2port_air",
            "A3_Air_F_Beta_Heli_Attack_02",
            "rhs_c_mig29",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "JS_JC_SU35",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "rhs_c_air",
            "RHS_US_A2_AirImport",
            "RHSGREF_c_A29",
            "rhs_vehicle_sounds",
            "rhs_c_mi28",
            "rhs_c_kamaz",
            "rhs_c_vehiclesounds",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_02",
            "A3_Soft_F_Enoch_Truck_02",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Drones_F_Air_F_Gamma_UAV_02",
            "LoiteringMunitionUAVs"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_RU_VMF {
        units[] = {
            "ru_vmf_sergeant",
            "ru_vmf_efreitor",
            "ru_vmf_rifleman_ak12",
            "ru_vmf_rifleman_ak15",
            "ru_vmf_grenadier_gp34",
            "ru_vmf_grenadier_rpg",
            "ru_vmf_autorifleman",
            "ru_vmf_machinegunner",
            "ru_vmf_marksman",
            "ru_vmf_engineer",
            "ru_vmf_medic",
            "ru_vmf_officer",
            "ru_vmf_at_specialist",
            "ru_vmf_aa_specialist",
            "ru_vmf_crewman",
            "ru_vmf_worker",
            "ru_vmf_uav_operator",
            "ru_vmf_driver",
            "ru_vmf_mortarman_gun",
            "ru_vmf_mortarman_bipod",
            "ru_vmf_heli_pilot",
            "ru_vmf_heli_crew",
            "ru_vmf_jet_pilot",
            "ru_vmf_spetsnaz_ak12",
            "ru_vmf_spetsnaz_ak103",
            "ru_vmf_spetsnaz_ak104",
            "ru_vmf_spetsnaz_ak74m",
            "ru_vmf_spetsnaz_rpk74m",
            "ru_vmf_spetsnaz_svd",
            "ru_vmf_spetsnaz_pilot",
            "ru_vmf_btr60pb",
            "ru_vmf_btr70",
            "ru_vmf_btr80a",
            "ru_vmf_bm21",
            "ru_vmf_gaz_normal",
            "ru_vmf_gaz_armed",
            "ru_vmf_gaz_unarmed",
            "ru_vmf_bmp1",
            "ru_vmf_bmp2",
            "ru_vmf_brdm2",
            "ru_vmf_brdm2_at",
            "ru_vmf_ural_normal",
            "ru_vmf_ural_ammo",
            "ru_vmf_ural_fuel",
            "ru_vmf_ural_open",
            "ru_vmf_ural_repair",
            "ru_vmf_salvager",
            "ru_vmf_ural_aa",
            "ru_vmf_t72b_1989",
            "ru_vmf_t72b3_2016",
            "ru_vmf_t80bv",
            "ru_vmf_t80um",
            "ru_vmf_t90sa_2004",
            "ru_vmf_t90sm",
            "ru_vmf_ka60",
            "ru_vmf_ka52",
            "ru_vmf_mi8_normal",
            "ru_vmf_mi8_gunship",
            "ru_vmf_mi24g",
            "ru_vmf_su25",
            "ru_vmf_su35",
            "ru_vmf_mig29sm",
            "ru_vmf_k40a",
            "ru_vmf_k40b"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops",
            "A3_Characters_F",
            "rhs_cti_insurgents",
            "rhsgref_c_troops",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhs_c_a2port_armor",
            "rhs_c_btr",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhsgref_c_a2port_armor",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "rhs_c_a2port_car",
            "rhs_c_vehiclesounds",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "rhssaf_c_vehicles",
            "rhsgref_c_vehicles_ret",
            "rhs_c_cars",
            "A3_Soft_F_MRAP_02",
            "rhs_c_bmp",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a3retex",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Beta_Heli_Transport_01",
            "rhsusf_c_melb",
            "rhsgref_c_air",
            "rhs_c_a2port_air",
            "A3_Air_F_Beta_Heli_Attack_02",
            "rhs_vehicle_sounds",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "JS_JC_SU35",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "rhs_c_air",
            "rhs_c_mig29",
            "RHS_US_A2_AirImport",
            "RHSGREF_c_A29",
            "su35_rhs_russian",
            "A3_Drones_F_Air_F_Gamma_UAV_02",
            "LoiteringMunitionUAVs"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_US_USMC {
        units[] = {
            "us_usmc_sergeant",
            "us_usmc_lance_corporal",
            "us_usmc_rifleman_m16",
            "us_usmc_rifleman_m4a1",
            "us_usmc_rifleman_at",
            "us_usmc_autorifleman_m249",
            "us_usmc_machinegunner",
            "us_usmc_marksman",
            "us_usmc_sniper",
            "us_usmc_corpsman",
            "us_usmc_engineer",
            "us_usmc_aa_specialist",
            "us_usmc_missileman",
            "us_usmc_officer",
            "us_usmc_crewman",
            "us_usmc_worker",
            "us_usmc_heli_pilot",
            "us_usmc_heli_crewman",
            "us_usmc_jet_pilot",
            "us_usmc_marsoc_chief",
            "us_usmc_marsoc_heli_pilot",
            "us_usmc_marsoc_eod",
            "us_usmc_marsoc_marksman",
            "us_usmc_uh80",
            "us_usmc_marsoc_mk16",
            "us_usmc_marsoc_mk17",
            "us_usmc_marsoc_m249",
            "us_usmc_marsoc_eglm",
            "us_usaf_a10a",
            "us_usaf_ah64d",
            "us_usaf_f22a",
            "us_usaf_c130j",
            "us_usmc_ch47f",
            "us_usmc_ch53e",
            "us_usmc_ah1z",
            "us_usmc_uh1y_unarmed",
            "us_usmc_uh1y_rocket",
            "us_usmc_uh1y_armed",
            "us_usmc_uh60m",
            "us_usmc_uh60m_ews",
            "us_usmc_ah6m",
            "us_usmc_mh6m",
            "us_usmc_oh6m",
            "us_usmc_m142",
            "us_usmc_m2a3",
            "us_usmc_m2a3_b1",
            "us_usmc_m2a3_b2",
            "us_usmc_m1a1fep",
            "us_usmc_m1a2sepv1_t1",
            "us_usmc_m1a2sepv1_t2",
            "us_usmc_m1a2sepv2",
            "us_usmc_m6a2_aa",
            "us_usmc_m977a4",
            "us_usmc_m977a4_ammo",
            "us_usmc_m977a4_repair",
            "us_usmc_m977a4_fuel",
            "us_usmc_m1078a1",
            "us_usmc_m1078a1_flatbed",
            "us_usmc_m1123_half",
            "us_usmc_m1123_open",
            "us_usmc_m1123",
            "us_usmc_m1126_m2",
            "us_usmc_m1126_mk19",
            "us_usmc_m1134_aa",
            "us_usmc_m113a3_ammo",
            "us_usmc_m113a3_m2",
            "us_usmc_m113a3_mk19",
            "us_usmc_m113a3_unarmed",
            "us_usmc_m1151a1",
            "us_usmc_m1151a1_crows_m2",
            "us_usmc_m1151a1_crows_mk19",
            "us_usmc_m1151a1_m2",
            "us_usmc_m1151a1_m240",
            "us_usmc_m1151a1_mk19",
            "us_usmc_marsoc_m4a4",
            "us_usmc_m1152a1_ammo",
            "us_usmc_marsoc_m136",
            "us_usmc_at_specialist",
            "us_usmc_salvager",
            "us_usmc_grenadier_m16a4",
            "us_usmc_grenadier_m4a1",
            "us_usmc_mortarman_gun",
            "us_usmc_mortarman_bipod",
            "us_usmc_uav_operator",
            "us_usaf_mq4a",
            "us_usaf_mq4b",
            "us_usaf_a29",
            "us_usaf_f15ex",
            "us_usaf_f16c"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsusf_c_troops",
            "A3_Characters_F",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "A3_Air_F_Beta_Heli_Transport_01",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "rhsusf_c_melb",
            "rhsgref_c_air",
            "RHS_US_A2_AirImport",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "rhs_c_a2port_air",
            "rhs_c_air",
            "rhs_c_mig29",
            "RHSGREF_c_A29",
            "rhssaf_c_vehicles",
            "A3_Air_F_Beta_Heli_Attack_01",
            "rhsusf_c_f22",
            "A3_Air_F_Beta_Heli_Transport_02",
            "rhsusf_c_ch53",
            "A3_Air_F_EPB_Heli_Light_03",
            "rhsusf_c_himars",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Gamma_Truck_01",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_mtvr",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsgref_c_vehicles_ret",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "rhsusf_c_m109",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "RHSUSF_c_vehicleSounds",
            "rhsusf_vehicles",
            "A3_Soft_F_MRAP_01",
            "A3_Soft_F_Exp_MRAP_01",
            "rhsusf_c_stryker",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_btr",
            "rhsgref_c_a2port_armor",
            "rhsusf_c_m11xx",
            "A3_Soft_F_Exp_Truck_01",
            "rhsusf_c_m1117",
            "A3_Drones_F_Air_F_Gamma_UAV_02",
            "LoiteringMunitionUAVs"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
    class AKO_US_RG {
        units[] = {
            "us_rg_rifleman_m4",
            "us_rg_sergeant",
            "us_rg_rifleman_mk16",
            "us_rg_rifleman_mk17",
            "us_rg_corporal",
            "us_rg_auto_rifleman",
            "us_rg_mortarman_gun",
            "us_rg_mortarman_bipod",
            "us_rg_officer",
            "us_rg_medic",
            "us_rg_crewman",
            "us_rg_engineer",
            "us_rg_marksman",
            "us_rg_machine_gunner",
            "us_rg_jet_pilot",
            "us_rg_helicopter_pilot",
            "us_rg_helicopter_crew",
            "us_rg_worker",
            "us_rg_uav_operator",
            "us_rg_aa_specialist",
            "us_rg_at_specialist",
            "us_dvg_operator_m4",
            "us_dvg_operator_mk16",
            "us_dvg_operator_mk17",
            "us_dvg_operator_mk48",
            "us_dvg_uav_operator",
            "us_dvg_heli_pilot",
            "us_rg_uh80",
            "us_rg_uh60m",
            "us_rg_uh60m_ews",
            "us_dvg_ah6m",
            "us_dvg_mh6m",
            "us_dvg_oh6m",
            "us_rg_m142",
            "us_rg_m2a3",
            "us_rg_m2a3_b1",
            "us_rg_m2a3_b2",
            "us_rg_m1a1fep",
            "us_rg_m1a2sepv1_t1",
            "us_rg_m1a2sepv1_t2",
            "us_rg_m1a2sepv2",
            "us_rg_m6a2_aa",
            "us_rg_m977a4",
            "us_rg_m977a4_ammo",
            "us_rg_m977a4_repair",
            "us_rg_m977a4_fuel",
            "us_rg_m1078a1",
            "us_rg_m1078a1_flatbed",
            "us_rg_m1123_half",
            "us_rg_m1123_open",
            "us_rg_m1123",
            "us_rg_m1126_m2",
            "us_rg_m1126_mk19",
            "us_rg_m1134_aa",
            "us_rg_m113a3_ammo",
            "us_rg_m113a3_m2",
            "us_rg_m113a3_mk19",
            "us_rg_m113a3_unarmed",
            "us_rg_m1151a1",
            "us_rg_m1151a1_crows_m2",
            "us_rg_m1151a1_crows_mk19",
            "us_rg_m1151a1_m2",
            "us_rg_m1151a1_m240",
            "us_rg_m1151a1_mk19",
            "us_rg_m1152a1_ammo",
            "us_rg_salvager"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsusf_c_troops",
            "A3_Characters_F",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "A3_Air_F_Beta_Heli_Transport_01",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "rhsusf_c_melb",
            "rhsgref_c_air",
            "RHS_US_A2_AirImport",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "rhs_c_a2port_air",
            "rhs_c_air",
            "rhs_c_mig29",
            "RHSGREF_c_A29",
            "rhssaf_c_vehicles",
            "A3_Air_F_Beta_Heli_Attack_01",
            "rhsusf_c_f22",
            "A3_Air_F_Beta_Heli_Transport_02",
            "rhsusf_c_ch53",
            "A3_Air_F_EPB_Heli_Light_03",
            "rhsusf_c_himars",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Gamma_Truck_01",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_mtvr",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsgref_c_vehicles_ret",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "rhsusf_c_m109",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "RHSUSF_c_vehicleSounds",
            "rhsusf_vehicles",
            "A3_Soft_F_MRAP_01",
            "A3_Soft_F_Exp_MRAP_01",
            "rhsusf_c_stryker",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_btr",
            "rhsgref_c_a2port_armor",
            "rhsusf_c_m11xx",
            "A3_Soft_F_Exp_Truck_01",
            "rhsusf_c_m1117",
            "A3_Drones_F_Air_F_Gamma_UAV_02",
            "LoiteringMunitionUAVs"
        };
        author = "Kaga No Kami";
        authors[] = {"Kaga No Kami"};
    };
    class AKO_US_USAF {
        units[] = {
            "us_usaf_jet_pilot",
            "us_usaf_a10a",
            "us_usaf_ah64d",
            "us_usaf_f22a",
            "us_usaf_c130j",
            "us_usaf_mq4a",
            "us_usaf_mq4b",
            "us_usaf_a29",
            "us_usaf_f15ex",
            "us_usaf_f16c"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhsusf_c_troops",
            "A3_Characters_F",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "A3_Air_F_Beta_Heli_Transport_01",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "rhsusf_c_melb",
            "rhsgref_c_air",
            "RHS_US_A2_AirImport",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "rhs_c_a2port_air",
            "rhs_c_air",
            "rhs_c_mig29",
            "RHSGREF_c_A29",
            "rhssaf_c_vehicles",
            "A3_Air_F_Beta_Heli_Attack_01",
            "rhsusf_c_f22",
            "A3_Air_F_Beta_Heli_Transport_02",
            "rhsusf_c_ch53",
            "A3_Air_F_EPB_Heli_Light_03",
            "rhsusf_c_himars",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Gamma_Truck_01",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_mtvr",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsgref_c_vehicles_ret",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "rhsusf_c_m109",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m113",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "RHSUSF_c_vehicleSounds",
            "rhsusf_vehicles",
            "A3_Soft_F_MRAP_01",
            "A3_Soft_F_Exp_MRAP_01",
            "rhsusf_c_stryker",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_btr",
            "rhsgref_c_a2port_armor",
            "rhsusf_c_m11xx",
            "A3_Soft_F_Exp_Truck_01",
            "rhsusf_c_m1117",
            "A3_Drones_F_Air_F_Gamma_UAV_02",
            "LoiteringMunitionUAVs"
        };
        author = "Kaga No Kami";
        authors[] = {"Kaga No Kami"};
    };
};

class CBA_Extended_EventHandlers_base;

class CfgFactionClasses {
    class AKO_AL_ADF {
        displayName = "Ako's Altis (ADF)";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        priority = 0;
    };
    class AKO_TA_TLA {
        displayName = "Ako's Tanoa (TLA)";
        side = 2;
        flag = "\A3\Ui_f\data\Map\Markers\Flags\tanoa_ca.paa";
        icon = "\A3\Ui_f\data\Map\Markers\Flags\tanoa_ca.paa";
        priority = 0;
    };
    class AKO_TK_ISIS {
        displayName = "Ako's Takistan (ISIS)";
        side = 2;
        flag = "\CUP\BaseConfigs\CUP_BaseConfigs\data\Flags\flag_tkm_co.paa";
        icon = "\CUP\BaseConfigs\CUP_BaseConfigs\data\Flags\flag_tkm_co.paa";
        priority = 0;
    };
    class AKO_RU_MSV {
        displayName = "Ako's Russia (MSV)";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        priority = 0;
    };
    class AKO_RU_VDV {
        displayName = "Ako's Russia (VDV)";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        priority = 0;
    };
    class AKO_RU_VMF {
        displayName = "Ako's Russia (VMF)";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vmf_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vmf_CO.paa";
        priority = 0;
    };
    class AKO_US_USMC {
        displayName = "Ako's USA (USMC)";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
    class AKO_US_RG {
        displayName = "Ako's USA (RANGERS)";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
    class AKO_US_RG {
        displayName = "Ako's USA (AIR FORCE)";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class AKO_AL_ADF {
            name = "Ako's Altis (ADF)";
        };
        class AKO_TA_TLA {
            name = "Ako's Tanoa (TLA)";
        };
        class AKO_TK_ISIS {
            name = "Ako's Takistan (ISIS)";
        };

    };
    class EAST {

        class AKO_RU_MSV {
            name = "Ako's Russia (MSV)";
        };
        class AKO_RU_VDV {
            name = "Ako's Russia (VDV)";
        };
        class AKO_RU_VMF {
            name = "Ako's Russia (VMF)";
        };
    };
    class WEST {

        class AKO_US_USMC {
            name = "Ako's America (USMC)";
        };
        class AKO_US_RG {
            name = "Ako's America (RANGERS)";
        };
        class AKO_US_USAF {
            name = "Ako's America (AIR FORCE)";
        };
    };
};

class CfgVehicles {
    
    // BLUFOR // ---------------------------------------
    #include "BLUFOR\USMC\Cfg_USMC_Infantry.hpp"
    #include "BLUFOR\USMC\Cfg_USMC_Infantry_Desert.hpp"
    #include "BLUFOR\USMC\Cfg_USMC_Ground.hpp"
    #include "BLUFOR\USMC\Cfg_USMC_Air.hpp"

    #include "BLUFOR\USRG\Cfg_USRG_Infantry.hpp"
    #include "BLUFOR\USRG\Cfg_USRG_Ground.hpp"
    #include "BLUFOR\USRG\Cfg_USRG_Air.hpp"

    #include "BLUFOR\USRG\Cfg_USAF_Combined.hpp"

    // REDFOR // ---------------------------------------
    #include "REDFOR\MSV\Cfg_MSV_Infantry.hpp"
    #include "REDFOR\MSV\Cfg_MSV_Ground.hpp"

    #include "REDFOR\VDV\Cfg_VDV_Infantry.hpp"
    #include "REDFOR\VDV\Cfg_VDV_Infantry_Desert.hpp"
    #include "REDFOR\VDV\Cfg_VDV_Ground.hpp"
    #include "REDFOR\VDV\Cfg_VDV_Air.hpp"

    #include "REDFOR\VMF\Cfg_VMF_Infantry.hpp"

    // INDEPENDENT // ----------------------------------
    #include "INDEPENDENT\ADF\Cfg_ADF_Combined.hpp"
    #include "INDEPENDENT\TLA\Cfg_TLA_Combined.hpp"
    #include "INDEPENDENT\ISIS\Cfg_ISIS_Combined.hpp"
}
