//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class AKO_RU_MSV_ {
        displayName = "Ako's Russia (MSV)";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        priority = 0;
    };
};