class CfgPatches {
    class AKO_RU_MSV_ {
        units[] = {
            "rifleman_ak12",
            "rifleman_ak74m",
            "rifleman_akm",
            "sergeant",
            "crewman",
            "tank_crewman",
            "efreitor",
            "machinegunner",
            "marksman",
            "engineer",
            "medic",
            "grenadier_rpg",
            "aa_specialist",
            "at_specialist",
            "officer",
            "worker",
            "btr80a",
            "btr70",
            "t72b_1989",
            "t72b3_2012",
            "t80u",
            "t80um",
            "t90_1992",
            "t90a_2006",
            "t90sm",
            "bmp1",
            "bmp2",
            "bmp3",
            "bmp3_vesna"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops",
            "A3_Characters_F",
            "rhs_cti_insurgents",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "cba_xeh",
            "rhs_c_btr",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhs_c_a2port_armor",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "rhs_c_t72",
            "rhs_c_vehiclesounds",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_tanks"
        };
        author = "Akosovski";
        authors[] = {"Akosovski"};
    };
};
