//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhs_msv_emr_rifleman;
    class rhs_msv_emr_rifleman_OCimport_01 : rhs_msv_emr_rifleman { scope = 0; class EventHandlers; };
    class rhs_msv_emr_rifleman_OCimport_02 : rhs_msv_emr_rifleman_OCimport_01 { class EventHandlers; };

    class rhs_btr80a_msv;
    class rhs_btr80a_msv_OCimport_01 : rhs_btr80a_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr80a_msv_OCimport_02 : rhs_btr80a_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class Commander_Out;
        };
    };

    class rhs_btr70_msv;
    class rhs_btr70_msv_OCimport_01 : rhs_btr70_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr70_msv_OCimport_02 : rhs_btr70_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhs_t72bc_tv;
    class rhs_t72bc_tv_OCimport_01 : rhs_t72bc_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t72bc_tv_OCimport_02 : rhs_t72bc_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t72bd_tv;
    class rhs_t72bd_tv_OCimport_01 : rhs_t72bd_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t72bd_tv_OCimport_02 : rhs_t72bd_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t80u;
    class rhs_t80u_OCimport_01 : rhs_t80u { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t80u_OCimport_02 : rhs_t80u_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t80um;
    class rhs_t80um_OCimport_01 : rhs_t80um { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t80um_OCimport_02 : rhs_t80um_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t90_tv;
    class rhs_t90_tv_OCimport_01 : rhs_t90_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t90_tv_OCimport_02 : rhs_t90_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t90a_tv;
    class rhs_t90a_tv_OCimport_01 : rhs_t90a_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t90a_tv_OCimport_02 : rhs_t90a_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_t90sm_tv;
    class rhs_t90sm_tv_OCimport_01 : rhs_t90sm_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t90sm_tv_OCimport_02 : rhs_t90sm_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_bmp1_msv;
    class rhs_bmp1_msv_OCimport_01 : rhs_bmp1_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp1_msv_OCimport_02 : rhs_bmp1_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class Com_BMP1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };

    class rhs_bmp2_msv;
    class rhs_bmp2_msv_OCimport_01 : rhs_bmp2_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp2_msv_OCimport_02 : rhs_bmp2_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };

    class rhs_bmp3_late_msv;
    class rhs_bmp3_late_msv_OCimport_01 : rhs_bmp3_late_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp3_late_msv_OCimport_02 : rhs_bmp3_late_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class GPMGTurret2;
        };
    };

    class rhs_bmp3mera_msv;
    class rhs_bmp3mera_msv_OCimport_01 : rhs_bmp3mera_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp3mera_msv_OCimport_02 : rhs_bmp3mera_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class GPMGTurret2;
        };
    };

// ----------------------------------------------------------------

    class ru_msv_rifleman_ak12 : rhs_msv_emr_rifleman_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Rifleman (AK-12)";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK12_black"};
        respawnWeapons[] = {"CUP_arifle_AK12_black"};

        magazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK12_M","CUP_30Rnd_545x39_AK12_M"};

        backpack = "rhs_rd54_emr1";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK12_black","","","",{"CUP_30Rnd_545x39_AK12_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",2},{"CUP_30Rnd_545x39_AK12_M",8,30}}},{"rhs_rd54_emr1",{{"FirstAidKit",5},{"CUP_30Rnd_545x39_AK12_M",5,30},{"rhs_mag_rgo",3,1}}},"rhs_6b7_1m_olive","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_rifleman_ak74m : ru_msv_rifleman_ak12 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Rifleman (AK-74M)";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M"};
        respawnWeapons[] = {"CUP_arifle_AK74M"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{},"rhs_6b7_1m_emr","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_rifleman_akm : ru_msv_rifleman_ak74m {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Rifleman (AKM)";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_bakelite_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_762x39_AK47_bakelite_M",9,30}}},{},"rhs_6b7_1m","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_sergeant : ru_msv_rifleman_akm {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Sergeant";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_grn","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_grn","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_GL","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AK74M_GL","Binocular"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_1Rnd_HE_GP25_M","CUP_30Rnd_545x39_AK74_plum_M","CUP_1Rnd_HE_GP25_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_1Rnd_HE_GP25_M","CUP_30Rnd_545x39_AK74_plum_M","CUP_1Rnd_HE_GP25_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_GL","rhs_acc_dtk","","rhs_acc_pkas",{"CUP_30Rnd_545x39_AK74_plum_M",30},{"CUP_1Rnd_HE_GP25_M",1},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_grn",{{"CUP_30Rnd_545x39_AK74_plum_M",8,30},{"rhs_mag_rgo",4,1},{"CUP_1Rnd_HE_GP25_M",10,1}}},{},"rhs_6b7_1m_emr_ess","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_crewman : ru_msv_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Crewman";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_light","rhs_tsh4_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_tsh4_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U"};
        respawnWeapons[] = {"CUP_arifle_AKS74U"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"rhs_mag_rgo",2,1},{"CUP_30Rnd_545x39_AK74M_M",4,30}}},{},"rhs_tsh4_ess","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_tank_crewman : ru_msv_crewman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Tank Crewman";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_light","rhs_6b48","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_6b48","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U"};
        respawnWeapons[] = {"CUP_arifle_AKS74U"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"rhs_mag_rgo",2,1},{"CUP_30Rnd_545x39_AK74_plum_M",5,30}}},{},"rhs_6b48","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_efreitor : ru_msv_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Efreitor";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M","rhs_weap_rpg26","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AK74M","rhs_weap_rpg26","Binocular"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","rhs_rpg26_mag","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","rhs_rpg26_mag","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","rhs_acc_perst1ik_ris","rhs_acc_1p63",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{"rhs_weap_rpg26","","","",{"rhs_rpg26_mag",1},{},""},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74_plum_M",8,30}}},{},"rhs_6b7_1m_emr_ess","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_machinegunner : ru_msv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Machine Gunner";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_mg","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_mg","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_PKM"};
        respawnWeapons[] = {"CUP_lmg_PKM"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M"};

        backpack = "rhs_tortila_emr";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_PKM","","","",{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",100},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_mg",{{"FirstAidKit",2},{"rhs_mag_rgo",4,1},{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",2,100}}},{"rhs_tortila_emr",{{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M",6,100}}},"rhs_6b7_1m_ess","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_marksman : ru_msv_machinegunner {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Marksman";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_SVD"};
        respawnWeapons[] = {"CUP_srifle_SVD"};

        magazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};
        respawnMagazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_SVD","","","CUP_optic_PSO_3_open",{"CUP_10Rnd_762x54_SVD_M",10},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"FirstAidKit",1},{"CUP_10Rnd_762x54_SVD_M",10,10},{"rhs_mag_rgo",4,1}}},{},"rhs_beanie_green","G_Bandanna_oli",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_engineer : ru_msv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Engineer";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M"};
        respawnWeapons[] = {"CUP_arifle_AK74M"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "rhs_assault_umbts_engineer_empty";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{"rhs_assault_umbts_engineer_empty",{{"ToolKit",2}}},"rhs_6b7_1m_emr","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_medic : ru_msv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Medic";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M"};
        respawnWeapons[] = {"CUP_arifle_AK74M"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{"rhs_sidor",{{"Medikit",1},{"FirstAidKit",6}}},"rhs_6b7_1m_ess","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_grenadier_rpg : ru_msv_rifleman_akm {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Grenadier RPG";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M","rhs_weap_rpg7"};
        respawnWeapons[] = {"CUP_arifle_AK74M","rhs_weap_rpg7"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","rhs_rpg7_PG7VL_mag","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","rhs_rpg7_PG7VL_mag","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "rhs_rpg_6b3";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{"rhs_weap_rpg7","","","rhs_acc_pgo7v3",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{"rhs_rpg_6b3",{{"rhs_rpg7_PG7VL_mag",2,1},{"rhs_rpg7_OG7V_mag",2,1}}},"rhs_6b7_1m_ess","G_Bandanna_oli",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_aa_specialist : ru_msv_grenadier_rpg {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV AA Specialist";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M","rhs_weap_igla"};
        respawnWeapons[] = {"CUP_arifle_AK74M","rhs_weap_igla"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{"rhs_weap_igla","","","",{},{},""},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{},"rhs_6b7_1m_olive","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_at_specialist : ru_msv_aa_specialist {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV AT Specialist";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_rifleman","rhs_6b7_1m_emr_ess","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M","launch_O_Vorona_green_F"};
        respawnWeapons[] = {"CUP_arifle_AK74M","launch_O_Vorona_green_F"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","Vorona_HEAT","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","Vorona_HEAT","CUP_30Rnd_545x39_AK74_plum_M"};

        backpack = "rhs_tortila_emr";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{"launch_O_Vorona_green_F","","","",{"Vorona_HEAT",1},{},""},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_rifleman",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74_plum_M",8,30}}},{"rhs_tortila_emr",{{"Vorona_HEAT",2,1}}},"rhs_6b7_1m_emr_ess","G_Bandanna_khk",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_officer : ru_msv_efreitor {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Officer";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45_light","rhs_fieldcap_digi2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45_light","rhs_fieldcap_digi2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AK74M","Binocular"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M","rhs_acc_dtk","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45_light",{{"rhs_mag_rgo",4,1},{"CUP_30Rnd_545x39_AK74_plum_M",4,30}}},{},"rhs_fieldcap_digi2","G_Aviator",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_worker : ru_msv_officer {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV Worker";
        side = 0;
        faction = "AKO_RU_MSV_";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b45","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b45","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"rhs_uniform_emr_patchless",{{"FirstAidKit",5}}},{"rhs_6b45",{}},{},"rhs_6b7_1m_olive","G_Bandanna_khk",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class ru_msv_btr80a : rhs_btr80a_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BTR-80A";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class CommanderOptics : CommanderOptics { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_01_std_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_02_std_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_03_std_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_btr70 : rhs_btr70_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BTR-70";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class CommanderOptics : CommanderOptics { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_btr70\data\btr70_1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_btr70\data\btr70_2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t72b_1989 : rhs_t72bc_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-72B (1989)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t72\data\rhs_t72b_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t72\data\rhs_t72b_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t72\data\rhs_t72b_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_t72\data\rhs_t72b_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_t72\data\rhs_t72b_05_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t72b3_2012 : rhs_t72bd_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-72B3 (2012)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t72\data\rhs_t72b_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_t72\data\rhs_t72b_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_t72\data\rhs_t72b_05_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_turret_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t80u : rhs_t80u_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-80U";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_03_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t80um : rhs_t80um_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-80UM";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_02b_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t80u\data\rhs_t80u_03_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t90_1992 : rhs_t90_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-90 (1992)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t72\data\rhs_t72b_02d_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t72\data\rhs_t72b_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_t72\data\rhs_t72b_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_t72\data\rhs_t72b_05_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_t72\data\rhs_t90parts_co.paa'];_unit setObjectTextureGlobal [6,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_02_co.paa'];_unit setObjectTextureGlobal [7,''];_unit setObjectTextureGlobal [8,'rhsafrf\addons\rhs_t72\data\rhs_dazzler_co.paa'];_unit setObjectTextureGlobal [9,'rhsafrf\addons\rhs_t72\data\rhs_dazzler_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t90a_2006 : rhs_t90a_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-90A (2006)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t72\data\rhs_t72b_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_t72\data\rhs_t72b_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_t72\data\rhs_t72b_05_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_t72\data\rhs_t90parts_co.paa'];_unit setObjectTextureGlobal [6,'rhsafrf\addons\rhs_t72\data\rhs_t90a_02_co.paa'];_unit setObjectTextureGlobal [7,''];_unit setObjectTextureGlobal [8,'rhsafrf\addons\rhs_t72\data\rhs_dazzler_co.paa'];_unit setObjectTextureGlobal [9,'rhsafrf\addons\rhs_t72\data\rhs_dazzler_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_t90sm : rhs_t90sm_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV T-90SM";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "tank_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "tank_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t72\data\rhs_t72b_03_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_t72\data\rhs_t72b_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_t72\data\rhs_t90am_01_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_t72\data\rhs_t90am_02_co.paa'];_unit setObjectTextureGlobal [6,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_e_01_co.paa'];_unit setObjectTextureGlobal [7,'rhsafrf\addons\rhs_t72\data\rhs_t72b3_e_02_co.paa'];_unit setObjectTextureGlobal [8,'rhsafrf\addons\rhs_t72\data\rhs_t90parts_co.paa'];_unit setObjectTextureGlobal [9,'rhsafrf\addons\rhs_t72\data\rhs_t90a_02_co.paa'];_unit setObjectTextureGlobal [10,'rhsafrf\addons\rhs_t72\data\rhs_t90sm_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_bmp1 : rhs_bmp1_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BMP-1";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class Com_BMP1 : Com_BMP1 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp\textures\bmp_1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp\textures\bmp_2_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp\textures\bmp_3_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp\textures\bmp_4_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_bmp\textures\bmp_5_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_bmp\textures\bmp_6_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_bmp2 : rhs_bmp2_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BMP-2 (1986)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp\textures\bmp_1_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp\textures\bmp_2_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp\textures\bmp_3_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp\textures\bmp_4_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_bmp\textures\bmp_5_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_bmp\textures\bmp_6_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_bmp3 : rhs_bmp3_late_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BMP-3";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = "rhs_msv_rifleman"; };
            class GPMGTurret2 : GPMGTurret2 { gunnerType = "rhs_msv_rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_03_mod_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class ru_msv_bmp3_vesna : rhs_bmp3mera_msv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSV BMP-3 (Vesna-K/A)";
        side = 0;
        faction = "AKO_RU_MSV_";
        crew = "crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "crewman"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = "rhs_msv_rifleman"; };
            class GPMGTurret2 : GPMGTurret2 { gunnerType = "rhs_msv_rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_01_3mera_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_02_3mera_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_03_3m_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_04_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_bmp3\data\3m_era_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

};