//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class AKO_RU_VDV {
        displayName = "Ako's Russia (VDV)";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_vdv_CO.paa";
        priority = 0;
    };
};