//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhsgref_cdf_reg_rifleman;
    class rhsgref_cdf_reg_rifleman_OCimport_01 : rhsgref_cdf_reg_rifleman { scope = 0; class EventHandlers; };
    class rhsgref_cdf_reg_rifleman_OCimport_02 : rhsgref_cdf_reg_rifleman_OCimport_01 { class EventHandlers; };

    class rhsgref_cdf_t72bb_tv;
    class rhsgref_cdf_t72bb_tv_OCimport_01 : rhsgref_cdf_t72bb_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_t72bb_tv_OCimport_02 : rhsgref_cdf_t72bb_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhsgref_cdf_t80u_tv;
    class rhsgref_cdf_t80u_tv_OCimport_01 : rhsgref_cdf_t80u_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_t80u_tv_OCimport_02 : rhsgref_cdf_t80u_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhsgref_cdf_gaz66_zu23;
    class rhsgref_cdf_gaz66_zu23_OCimport_01 : rhsgref_cdf_gaz66_zu23 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_gaz66_zu23_OCimport_02 : rhsgref_cdf_gaz66_zu23_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class rhsgref_cdf_reg_uaz_dshkm;
    class rhsgref_cdf_reg_uaz_dshkm_OCimport_01 : rhsgref_cdf_reg_uaz_dshkm { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_reg_uaz_dshkm_OCimport_02 : rhsgref_cdf_reg_uaz_dshkm_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class rhsgref_cdf_reg_uaz_ags;
    class rhsgref_cdf_reg_uaz_ags_OCimport_01 : rhsgref_cdf_reg_uaz_ags { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_reg_uaz_ags_OCimport_02 : rhsgref_cdf_reg_uaz_ags_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class rhsgref_cdf_reg_uaz_spg9;
    class rhsgref_cdf_reg_uaz_spg9_OCimport_01 : rhsgref_cdf_reg_uaz_spg9 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_reg_uaz_spg9_OCimport_02 : rhsgref_cdf_reg_uaz_spg9_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class rhsgref_cdf_btr70;
    class rhsgref_cdf_btr70_OCimport_01 : rhsgref_cdf_btr70 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_btr70_OCimport_02 : rhsgref_cdf_btr70_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhsgref_cdf_bmp2d;
    class rhsgref_cdf_bmp2d_OCimport_01 : rhsgref_cdf_bmp2d { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_bmp2d_OCimport_02 : rhsgref_cdf_bmp2d_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };

    class rhsgref_cdf_bmp1;
    class rhsgref_cdf_bmp1_OCimport_01 : rhsgref_cdf_bmp1 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_bmp1_OCimport_02 : rhsgref_cdf_bmp1_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class Com_BMP1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };


    class al_adf_sergeant : rhsgref_cdf_reg_rifleman_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Sergeant";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36K_AG36"};
        respawnWeapons[] = {"CUP_arifle_G36K_AG36"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_G36","CUP_1Rnd_HE_M203"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_G36","CUP_1Rnd_HE_M203"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36K_AG36","","","CUP_optic_G36DualOptics",{"CUP_30Rnd_556x45_G36",30},{"CUP_1Rnd_HE_M203",1},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"CUP_30Rnd_556x45_G36",7,30},{"CUP_1Rnd_HE_M203",5,1},{"rhs_mag_m67",2,1}}},{},"rhsgref_helmet_pasgt_altis_lizard","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_rifleman : al_adf_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Rifleman";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36K_KSK_VFG"};
        respawnWeapons[] = {"CUP_arifle_G36K_KSK_VFG"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36K_KSK_VFG","","rhsusf_acc_anpeq15side_bk","CUP_optic_Aimpoint_5000",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_G36",8,30},{"rhs_mag_m67",3,1}}},{},"rhsgref_helmet_pasgt_altis_lizard","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_officer : al_adf_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Officer";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36K_RIS"};
        respawnWeapons[] = {"CUP_arifle_G36K_RIS"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36K_RIS","","","CUP_optic_CompM4",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_G36",7,30},{"rhs_mag_m67",3,1}}},{},"rhsgref_helmet_pasgt_altis_lizard","G_Aviator",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_aa_specialist : al_adf_sergeant {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF AA Specialist";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36C","rhs_weap_igla"};
        respawnWeapons[] = {"CUP_arifle_G36C","rhs_weap_igla"};

        magazines[] = {"CUP_30Rnd_556x45_G36","rhs_mag_9k38_rocket","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","rhs_mag_9k38_rocket","CUP_30Rnd_556x45_G36"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36C","","","CUP_optic_CompM4",{"CUP_30Rnd_556x45_G36",30},{},""},{"rhs_weap_igla","","","",{"rhs_mag_9k38_rocket",1},{},""},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_G36",10,30}}},{"rhs_sidor",{{"rhs_mag_9k38_rocket",1,1}}},"rhsgref_helmet_pasgt_altis_lizard","rhs_ess_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_at_specialist : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF AT Specialist";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36C_VFG_Carry","rhs_weap_rpg7"};
        respawnWeapons[] = {"CUP_arifle_G36C_VFG_Carry","rhs_weap_rpg7"};

        magazines[] = {"CUP_30Rnd_556x45_G36","rhs_rpg7_PG7VL_mag","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","rhs_rpg7_PG7VL_mag","CUP_30Rnd_556x45_G36"};

        backpack = "rhs_rpg_6b3";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36C_VFG_Carry","","","CUP_optic_G36DualOptics",{"CUP_30Rnd_556x45_G36",30},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"CUP_30Rnd_556x45_G36",10,30},{"rhs_mag_m67",2,1}}},{"rhs_rpg_6b3",{{"rhs_rpg7_PG7VL_mag",3,1}}},"rhsgref_helmet_pasgt_altis_lizard","rhs_ess_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_corporal : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Corporal";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36K_RIS"};
        respawnWeapons[] = {"CUP_arifle_G36K_RIS"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36K_RIS","","","CUP_optic_Aimpoint_5000",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_G36",8,30},{"rhs_mag_m67",2,1}}},{"CUP_O_RUS_Patrol_bag_Green",{{"FirstAidKit",5}}},"rhsgref_helmet_pasgt_altis_lizard","rhs_ess_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_autorifleman : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Auto Rifleman";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36A3"};
        respawnWeapons[] = {"CUP_arifle_G36A3"};

        magazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};
        respawnMagazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};

        backpack = "rhssaf_kitbag_smb";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36A3","","rhsusf_acc_anpeq15side_bk","CUP_optic_CompM4",{"CUP_100Rnd_556x45_BetaCMag",100},{},"CUP_Bipod_G36"},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"CUP_100Rnd_556x45_BetaCMag",5,100}}},{"rhssaf_kitbag_smb",{{"FirstAidKit",6},{"CUP_100Rnd_556x45_BetaCMag",5,100}}},"rhsgref_helmet_pasgt_altis_lizard","rhs_ess_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_crewman : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Crewman";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","H_HelmetCrew_I","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","H_HelmetCrew_I","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36C"};
        respawnWeapons[] = {"CUP_arifle_G36C"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36C","","","CUP_optic_CompM4",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_G36",10,30}}},{},"H_HelmetCrew_I","G_Bandanna_blk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_eod_specialist : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF EOD Specialist";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhssaf_bandana_smb","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhssaf_bandana_smb","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36KA3_grip"};
        respawnWeapons[] = {"CUP_arifle_G36KA3_grip"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36KA3_grip","","","CUP_optic_CompM4",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"CUP_30Rnd_556x45_G36",8,30},{"rhs_mag_m67",4,1}}},{"CUP_O_RUS_Patrol_bag_Green",{{"SatchelCharge_Remote_Mag",1,1},{"DemoCharge_Remote_Mag",3,1}}},"rhssaf_bandana_smb","rhs_googles_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_engineer : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Engineer";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36C"};
        respawnWeapons[] = {"CUP_arifle_G36C"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36C","","","CUP_optic_Aimpoint_5000",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",5},{"CUP_30Rnd_556x45_G36",7,30}}},{"CUP_O_RUS_Patrol_bag_Green",{{"FirstAidKit",3},{"ToolKit",2}}},"rhsgref_helmet_pasgt_altis_lizard","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_medic : al_adf_engineer {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Medic";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36C"};
        respawnWeapons[] = {"CUP_arifle_G36C"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36C","","","CUP_optic_Aimpoint_5000",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",5},{"CUP_30Rnd_556x45_G36",7,30}}},{"CUP_O_RUS_Patrol_bag_Green",{{"Medikit",2},{"FirstAidKit",5}}},"rhsgref_helmet_pasgt_altis_lizard","G_Spectacles",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_machinegunner : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Machine Gunner";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhsgref_helmet_pasgt_altis_lizard","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_M60E4"};
        respawnWeapons[] = {"CUP_lmg_M60E4"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M60E4","","","CUP_optic_Aimpoint_5000",{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",100},{},""},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"FirstAidKit",5},{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",1,100},{"rhs_mag_m67",1,1}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",6,100}}},"rhsgref_helmet_pasgt_altis_lizard","rhs_googles_black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_marksman : al_adf_rifleman {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF Marksman";
        side = 2;
        faction = "ako_al_adf";

        identityTypes[] = {"Head_Euro","LanguageCZ"};

        uniformClass = "rhsgref_uniform_altis_lizard";

        linkedItems[] = {"rhsgref_otv_khaki","rhs_beanie_green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_otv_khaki","rhs_beanie_green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_M14_DMR"};
        respawnWeapons[] = {"CUP_srifle_M14_DMR"};

        magazines[] = {"CUP_20Rnd_762x51_DMR","CUP_20Rnd_762x51_DMR"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_DMR","CUP_20Rnd_762x51_DMR"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M14_DMR","","","CUP_optic_LeupoldMk4",{"CUP_20Rnd_762x51_DMR",20},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"rhsgref_uniform_altis_lizard",{{"FirstAidKit",5}}},{"rhsgref_otv_khaki",{{"CUP_20Rnd_762x51_DMR",7,20}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_20Rnd_762x51_DMR",10,20}}},"rhs_beanie_green","G_Bandanna_oli",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_t72b : rhsgref_cdf_t72bb_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF T-72B";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_t80u : rhsgref_cdf_t80u_tv_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF T-80U";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_gaz66_aa : rhsgref_cdf_gaz66_zu23_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF GAZ-66 (AA)";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "rhsgref_cdf_reg_rifleman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "rhsgref_cdf_reg_officer"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_uaz_dshkm : rhsgref_cdf_reg_uaz_dshkm_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF UAZ-3151 (DShKM)";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_rifleman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_uaz_ags30 : rhsgref_cdf_reg_uaz_ags_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF UAZ-3151 (AGS-30)";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_rifleman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_uaz_spg9 : rhsgref_cdf_reg_uaz_spg9_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF UAZ-3151 (SPG-9)";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_rifleman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_btr70 : rhsgref_cdf_btr70_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF BTR-70";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_crewman"; };
            class CommanderOptics : CommanderOptics { gunnerType = "al_adf_crewman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_bmp2 : rhsgref_cdf_bmp2d_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF BMP-2";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_crewman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class al_adf_bmp1 : rhsgref_cdf_bmp1_OCimport_02 {
        author = "Akosovski";
        scope = 2;
        scopeCurator = 2;
        displayName = "ADF BMP-1";
        side = 2;
        faction = "ako_al_adf";
        crew = "al_adf_crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "al_adf_crewman"; };
            class Com_BMP1 : Com_BMP1 { gunnerType = "al_adf_crewman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};